### ISSUE TITLE
Design for button focus state

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/snapshot#1]
Need a visual indicator of focus that isn't the default outline box.

**Comment by paullewis** [comment]
![take-photo-highlight](https://user-images.githubusercontent.com/617438/27375884-5cbc8faa-5668-11e7-8af9-1ded99602677.png)

Seem okay?

**Comment by wibblymat** [comment]
Will that work for all of the buttons? Seems like it might be over the top for things like the front/back camera picker.

**Comment by paullewis** [comment]
I would still have the outline, just maybe `2px` rather than that one.

**Comment by wibblymat** [comment]
Ohhhh, the transparent ring is part of the button, not the outline. nvm, I was not paying proper attention. I thought you were suggesting adding the transparent bit to all of the buttons on focus :)
